


######## function definitions #############


PossibleCombinations  <- function(specnum) {
  # Calculates all possible combinations at each richness level 
  #   from 1 to spec.num
  # Calculates suggested replication at each richness level as follows:
  # if possible combinations <= 50; suggested replication = all combinations
  # if possible combinations > 50; suggested repl. = smallest multiple of 
  #   spec.num over 50
  # Calculates cumulative plotnumber
  #
  # Args:
  #   spec.num: integer, positive number giving the number of species in the
  #             species pool
  #
  # Returns:
  #   data.frame with four columns
  #   $Richness: richness levels from 1:specnum
  #   $numb.comb: number of possible combination at each Richness level
  #   $nrep: suggested replication at each richness level
  #   $sumrep: cummulative number of plots
  
possible.comb <- data.frame(Richness = 1:specnum)
possible.comb$numb.com <- choose(specnum, possible.comb$Richness)
possible.comb$nrep <- possible.comb$numb.com
if (max( possible.comb$nrep) > 50) {
  possible.comb[possible.comb$nrep > 50,]$nrep  <- ceiling(50/specnum)*specnum
}
possible.comb$sumrep <- cumsum(possible.comb$nrep)

return(possible.comb)

}

SpeciesList <- function(specnum) {
  # creates character vector with specnum species names. Species are named as 
  # follows: A_01, B_01 (...) Z_01, A_02, B_02 (...)
  #
  # Args:
  #   specnum: integer, positive number giving the number of species to be named
  #
  # Returns: character vector with specnum species names
  
  L <- length(LETTERS)
  NUM <- ceiling(specnum/L)
  spec.list <- paste(LETTERS, rep(formatC(1:NUM, width=2, flag="0"),each=L),
                     sep = "_")
  spec.list <- spec.list[1:specnum]
  return(spec.list)

}


SpeciesMatrix <- function(specnum = NULL, spec = NULL, expdesign = NULL) {
  # creates a species matrix with specnum species sample structure
  # speciefied by an experimental design data frame. If expdesign
  # is not provided, it is generated with the function PossibleCombinations()
  # and the number of species specified in specnum
  #
  # Args:
  #   specnum: integer, positive number giving the number of species in the
  #             species pool
  #   spec: charchter vector containing species names. length must match specnum 
  #   expdesign: dataframe as generated by PossibleCombinations()
  #
  # Returns:
  #   Species matrix with with presence absence data for species in plots
  #   rows are plots, species are column. Columnnames are species names, taken
  #   from specnum. Number of richness levels and number of replication
  #   per richness levels are taken from expdesign 
  
  if (is.null(specnum) & is.null(spec) & is.null( expdesign)) {
    stop ("you need to provide at least one of the three arguments,
          either specnum, spec or expedesign")
  }
  
  if ( is.null( specnum) & is.null( spec)) {
    specnum <- max( expdesign$Richness)
  }
  
  if ( is.null( specnum) & is.null( expdesign)) {
    specnum <-  length(spec)
  }
  
  if ( is.null ( spec)) {
    spec <- SpeciesList( specnum)
  }
  
  if ( is.null ( expdesign)) {
    expdesign <- PossibleCombinations( specnum)
  }
    
   
 # Error handling
  if ( FALSE %in% ( c("Richness", "nrep") %in% colnames( expdesign))) {
    stop("the experimental design data.frame (expdesign) must contain at least 
          the following columns: 
          Richness (the Richnes levels of the experiment) 
          nrep (the number of replication at each Richness level)")
  }
 
 if (! "sumrep" %in% colnames( expdesign)) {
   expdesign$sumrep <- cumsum( expdesign$nrep)
 }
 
 if (! "numb.com" %in% colnames( expdesign)) {
   expdesign.temp <- PossibleCombinations( specnum)
   expdesign$numb.com <- expdesign.temp[
     match(expdesign$Richness, expdesign.temp$Richness),]$numb.com
 }
 
 if (FALSE %in% (floor(expdesign[expdesign$numb.com > 50,]$nrep / 
       expdesign[expdesign$numb.com > 50,]$nrep) == 
   (expdesign[expdesign$numb.com > 50,]$nrep / 
   expdesign[expdesign$numb.com > 50,]$nrep))) {
   stop("number of replication is not an multiple of species number")
 }
 
 if (FALSE %in% (expdesign$nrep <= expdesign$numb.com)) {
   stop("number of replication exceeds number of possible combinations")
 }
 
 nplot <- sum(expdesign$nrep)
   
# empty species matrix
Spec.mat <- matrix( data = 0, nrow = nplot, ncol = specnum, 
                    dimnames = list( c(1:nplot),spec))

for (i in expdesign$Richness) {
  
  if (i == 1) { # fill monocultures
    for (n in 1:specnum) {
      Spec.mat[n,n]  <- 1
    }
    
   } else { n.Row <- which(expdesign$Richness == i)
            row.seq <- (expdesign$sumrep[n.Row-1]+1):expdesign$sumrep[n.Row]
            nTimes <- length(row.seq) / specnum
            SPECcomb <- data.frame(combn(spec,i))
            
            if (expdesign$numb.com[n.Row] <=50 ) { # if numb.com <= 50 -> all combinations
              
              plotSPEC <- SPECcomb
              
            } else { plotSPEC <- SPECcomb[,sample(which(SPECcomb == spec[1], 
                                                        arr.ind=T)[,2], nTimes)]
                     
                     for (S in 2:specnum) { #sample unique possible comb
                       plotSPEC <- cbind(plotSPEC, SPECcomb[,sample(
                         which(SPECcomb[ wich( !colnames( SPECcomb) %in%
                                                 colnames(plotSPEC)), ] ==
                                 SPEC[S], arr.ind=T)[,2], nTimes)])
                     }
                     
            }
            
            for (n in row.seq) { # fill rest of species matrix with presence absence
              spec.ind <- which(colnames(Spec.mat) %in% plotSPEC[,n-min(row.seq-1)])
              Spec.mat[n,spec.ind]  <- 1
            }
   }
}

return(Spec.mat)

}
            
              
                

