---
title: "Average slope vs number of functions"
output:
  html_notebook: default
  html_document: default
---

This script produces:

+ Figure 3

```{r, echo = FALSE}
library(dplyr)
library(tidyr)
library(ggplot2)
```


```{r}
source("functions_short.R")

specnum <- 15
funcnum <- 9

distribution = "runif"

FuncMat <- FunctionValue(specnum,funcnum, distribution, min = 0, max = 1)

func.names <- as.character( unique( FuncMat$Functions))

SpecMat <- SpeciesMatrix(specnum = specnum, maxrep = 200)

#method = "comp"
CF = 3
r = 0.25
```


```{r}
Slope_res <- data.frame(Estimate = numeric(),
                        `Std. Error` = numeric(),
                        `t value` = numeric(),    
                        `Pr(>|t|)` = numeric(),
                        nfunc = numeric(),
                        ncomp = numeric())

for (l in 0:funcnum) {
  
set.seed(999)

  if(l == 0) {
    method = "av"
  }  else {
    method = "comp"
    compfunc = func.names[1:l]
  }


AvFunc <- AverageFunction(SpecMat, FuncMat,
                          method = method, 
                          CF = CF, 
                          compfunc = compfunc,
                          r = r)

# standardize functions
AvFunc <- AvFunc %>% 
  select(Richness, one_of(func.names)) %>% 
  mutate_at(vars(one_of(func.names)), function(x) {x / max(x)})



for (i in seq_len(funcnum)) { #loop over all subsets of function of size 1:funcnum

  # all poosibel combination of i out of funcnum functions
  func_comb <- combn(func.names, i)
  

  for ( k  in seq_len(ncol(func_comb))) { #loop over all function combinations of size i
  
    # calculate mean function
    AvFunc_temp <- AvFunc %>%
      select(Richness, one_of(func_comb[ ,k])) %>% 
      mutate(meanFunction = rowMeans(.[func_comb[ ,k]]))
  
    # fit linear model
    mod <- lm(meanFunction ~ Richness, data = AvFunc_temp)
  
    # get slope estimate
    est <- summary(mod)$coefficients[2,]
    
    Slope_res <- data.frame(t(est)) %>% 
      mutate(., nfunc = i) %>% 
      mutate(ncomp = l) %>% 
      rbind(Slope_res, .)
  }
}
}


```


```{r, warnings = F}
Slope_res %>% 
  filter(ncomp %in% c(0,ceiling(funcnum/3),2*ceiling(funcnum/3),funcnum)) %>% 
  ggplot(aes(x = nfunc, y = Estimate, colour = as.factor(ncomp)))+
  geom_point(position = position_jitterdodge(jitter.width = 0.2, jitter.height = 0, dodge.width = 0.75),
             alpha = 0.5, shape = 21)+
  geom_smooth(method = "lm", se = F, size = 0.5, 
              position = position_dodge(width = 0.5))+
  scale_color_brewer(guide = guide_legend(title = "Number of functions\nwith complementarity"),
                     palette = "Set1")+
  scale_x_continuous(breaks = seq(1,funcnum,1))+
  labs(y = "Slope estimate",
       x = "Number of functions considered")+
  theme_classic()
  
  
  
```

